name: d_components
authors: [ Dejan Marlovic <dmarlovic83@gmail.com> ]
homepage: https://github.com/dejan-marlovic/d_components
description: A collection of generic angular components that I found useful and
  could not find among material components.
version: 0.2.1
publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.1
  angular_forms: ^3.0.0
  fo_components: 
    git: https://github.com/afpatmin/fo_components.git
  intl: ^0.17.0
  sass_builder: ^2.1.3

dependency_overrides:
  intl: ^0.17.0