name: d_components
author: Dejan Marlovic <dmarlovic83@gmail.com>
homepage: https://github.com/dejan-marlovic/d_components/
description: A collection of AngularDart components
version: 0.0.26

environment:
     sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  intl: ^0.15.1
  sass_builder: ^1.0.1
transformers:
- sass_builder:
    outputExtension: .scss.css
- angular