name: d_components
author: Dejan Marlovic <dmarlovic83@gmail.com>
homepage: https://github.com/dejan-marlovic/d_components/
description: A collection of AngularDart components
version: 0.0.26

environment:
  sdk: '>=2.0.0-dev.44.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+9
  angular_components: ^0.9.0-alpha+9
  angular_forms: ^2.0.0-alpha
  intl: ^0.15.2
  sass_builder: ^1.1.5