name: d_components
author: Dejan Marlovic <dmarlovic83@gmail.com>
homepage: https://github.com/dejan-marlovic/d_components/
description: A collection of AngularDart components
version: 0.0.26

environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+4
  angular_components: ^0.9.0-alpha+3
  angular_forms: 1.0.1-alpha+4
  intl: ^0.15.1
  sass_builder: ^1.1.2

dependency_overrides:
  analyzer: ^0.31.0-alpha.2

transformers:
- sass_builder:
    outputExtension: .css
- angular