name: d_components
author: Dejan Marlovic <dmarlovic83@gmail.com>
homepage: https://github.com/dejan-marlovic/d_components/
description: A collection of AngularDart components
version: 0.0.16
environment:
     sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^4.0.0-beta
  angular_components: ^0.6.0-beta
  intl: ^0.15.1
transformers:
  - angular

