name: d_components
author: Dejan Marlovic <dmarlovic83@gmail.com>
homepage: https://github.com/dejan-marlovic/d_components/
description: A collection of AngularDart components
version: 0.0.9
environment:
     sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.3+1
  intl: ^0.15.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'