name: d_components
description: A collection of generic angular components 
version: 0.2.0
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_forms: ^2.1.1
  intl: ^0.15.7
  sass_builder: ^2.1.2
