name: d_components
author: Dejan Marlovic <dmarlovic83@gmail.com>
homepage: https://github.com/dejan-marlovic/d_components/
description: A collection of AngularDart components
version: 0.0.26

environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'
dependencies:
  angular: ^5.0.0-beta+2
  angular_components: ^0.9.0-beta+1
  angular_forms: ^2.0.0-beta+2
  intl: ^0.15.7
  sass_builder: ^2.1.1